export const FETCH_ANIME_SUCCESS = 'FETCH_ANIME_SUCCESS'
export const FETCH_ANIME_LOADING = 'FETCH_ANIME_LOADING'

export const FETCH_USER_WATCHING_LOADING = 'FETCH_USER_WATCHING_LOADING'
export const FETCH_USER_WATCHING_SUCCESS = 'FETCH_USER_WATCHING_SUCCESS'

export const FETCH_USER_PLAN_LOADING = 'FETCH_USER_PLAN_LOADING'
export const FETCH_USER_PLAN_SUCCESS = 'FETCH_USER_PLAN_SUCCESS'

export const FETCH_USER_HOLD_LOADING = 'FETCH_USER_HOLD_LOADING'
export const FETCH_USER_HOLD_SUCCESS = 'FETCH_USER_HOLD_SUCCESS'

export const FETCH_USER_DROPPED_LOADING = 'FETCH_USER_DROPPED_LOADING'
export const FETCH_USER_DROPPED_SUCCESS = 'FETCH_USER_DROPPED_SUCCESS'

export const FETCH_USER_COMPLETED_LOADING = 'FETCH_USER_COMPLETED_LOADING'
export const FETCH_USER_COMPLETED_SUCCESS = 'FETCH_USER_COMPLETED_SUCCESS'

export const UPDATE_SEARCH_SUCCESS = 'UPDATE_SEARCH_SUCCESS'
export const UPDATE_SEARCH_LOADING = 'UPDATE_SEARCH_LOADING'

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN'

export const UPDATE_ANIME_STATUS_LOADING = 'UPDATE_ANIME_STATUS_LOADING'
export const UPDATE_ANIME_STATUS_SUCCESS = 'UPDATE_ANIME_STATUS_SUCCESS'

export const UPDATE_ANIME_EPISODE_LOADING = 'UPDATE_ANIME_EPISODE_LOADING'
export const UPDATE_ANIME_EPISODE_SUCCESS = 'UPDATE_ANIME_EPISODE_SUCCESS'