export const FETCH_ANIME_SUCCESS = 'FETCH_ANIME_SUCCESS'
export const FETCH_ANIME_LOADING = 'FETCH_ANIME_LOADING'

export const FETCH_USER_WATCHING_LOADING = 'FETCH_USER_WATCHING_LOADING'
export const FETCH_USER_WATCHING_SUCCESS = 'FETCH_USER_WATCHING_SUCCESS'

export const FETCH_USER_PLAN_LOADING = 'FETCH_USER_PLAN_LOADING'
export const FETCH_USER_PLAN_SUCCESS = 'FETCH_USER_PLAN_SUCCESS'

export const FETCH_USER_HOLD_LOADING = 'FETCH_USER_HOLD_LOADING'
export const FETCH_USER_HOLD_SUCCESS = 'FETCH_USER_HOLD_SUCCESS'

export const FETCH_USER_DROPPED_LOADING = 'FETCH_USER_DROPPED_LOADING'
export const FETCH_USER_DROPPED_SUCCESS = 'FETCH_USER_DROPPED_SUCCESS'

export const FETCH_USER_COMPLETED_LOADING = 'FETCH_USER_COMPLETED_LOADING'
export const FETCH_USER_COMPLETED_SUCCESS = 'FETCH_USER_COMPLETED_SUCCESS'

export const UPDATE_SEARCH_SUCCESS = 'UPDATE_SEARCH_SUCCESS'
export const UPDATE_SEARCH_LOADING = 'UPDATE_SEARCH_LOADING'
export const ADD_PREVIOUS_SEARCH = 'ADD_PREVIOUS_SEARCH'
export const CLEAR_PREVIOUS_SEARCH = 'CLEAR_PREVIOUS_SEARCH'

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN'

export const UPDATE_ANIME_STATUS_LOADING = 'UPDATE_ANIME_STATUS_LOADING'
export const UPDATE_ANIME_STATUS_SUCCESS = 'UPDATE_ANIME_STATUS_SUCCESS'

export const FETCH_ANIME_EPISODES_LOADING = 'FETCH_ANIME_EPISODES_LOADING'
export const FETCH_ANIME_EPISODES_SUCCESS = 'FETCH_ANIME_EPISODES_SUCCESS'

export const FETCH_ANIME_STATS_LOADING = 'FETCH_ANIME_STATS_LOADING'
export const FETCH_ANIME_STATS_SUCCESS = 'FETCH_ANIME_STATS_SUCCESS'
export const FETCH_ANIME_STATS_ERROR = 'FETCH_ANIME_STATS_ERROR'

//-------------------------------------------

// Character
export const FETCH_ANIME_CHARACTER_LOADING = 'FETCH_ANIME_CHARACTER_LOADING'
export const FETCH_ANIME_CHARACTER_SUCCESS = 'FETCH_ANIME_CHARACTER_SUCCESS'
export const FETCH_ANIME_CHARACTER_FAILED = 'FETCH_ANIME_CHARACTER_FAILED'

export const FETCH_CHARACTER_DETAIL_LOADING = 'FETCH_CHARACTER_DETAIL_LOADING'
export const FETCH_CHARACTER_DETAIL_SUCCESS = 'FETCH_CHARACTER_DETAIL_SUCCESS'
export const FETCH_CHARACTER_DETAIL_FAILED = 'FETCH_CHARACTER_DETAIL_FAILED'

// Related
export const FETCH_ANIME_RELATED_LOADING = 'FETCH_ANIME_RELATED_LOADING'
export const FETCH_ANIME_RELATED_SUCCESS = 'FETCH_ANIME_RELATED_SUCCESS'
export const FETCH_ANIME_RELATED_FAILED = 'FETCH_ANIME_RELATED_FAILED'

// Recommendation
export const FETCH_ANIME_RECOMMEND_LOADING = 'FETCH_ANIME_RECOMMEND_LOADING'
export const FETCH_ANIME_RECOMMEND_SUCCESS = 'FETCH_ANIME_RECOMMEND_SUCCESS'
export const FETCH_ANIME_RECOMMEND_FAILED = 'FETCH_ANIME_RECOMMEND_FAILED'

// MAL
export const FETCH_ANIME_STATUS_LOADING = 'FETCH_ANIME_STATUS_LOADING'
export const FETCH_ANIME_STATUS_SUCCESS = 'FETCH_ANIME_STATUS_SUCCESS'

export const UPDATE_LIST_ANIME_LOADING = 'UPDATE_LIST_ANIME_LOADING'
export const UPDATE_LIST_ANIME_SUCCESS = 'UPDATE_LIST_ANIME_SUCCESS'

export const DELETE_LIST_ANIME_LOADING = 'DELETE_LIST_ANIME_LOADING'
export const DELETE_LIST_ANIME_SUCCESS = 'DELETE_LIST_ANIME_SUCCESS'

export const LOGOUT = 'LOGOUT'

export const FETCH_ANIME_REVIEWS_LOADING = 'FETCH_ANIME_REVIEWS_LOADING'
export const FETCH_ANIME_REVIEWS_SUCCESS = 'FETCH_ANIME_REVIEWS_SUCCESS'

// ------------------

export const CHANGE_THEME = 'CHANGE_THEME'